# CircleCI v2.1 Config
version: 2.1

##
# orbs
#
# Orbs used in this pipeline
##
orbs:
  slack: circleci/slack@3.4.2
  pr-tools: mojaloop/pr-tools@0.1.8


##
# defaults
#
# YAML defaults templates, in alphabetical order
##

##
# Executors
#
# CircleCI Executors
##
executors:
  default-docker:
    working_directory: /home/circleci/project
    docker:
      - image: node:10.15-alpine

  default-machine:
    machine:
      image: ubuntu-1604:201903-01

##
# Jobs
#
# A map of CircleCI jobs
##
jobs:
  build_and_deploy_s3:
    executor: default-docker
    steps:
      - checkout
      - run:
          name: Install default dependencies
          command: |
            apk --no-cache add git
            apk --no-cache add ca-certificates
            apk --no-cache add curl
            apk --no-cache add openssh-client
            # for node 10.15-alpine, need to install from edge repo
            apk --no-cache add openjdk11 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
            apk --no-cache add graphviz
            apk add --no-cache -t build-dependencies make gcc g++ python libtool autoconf automake
            npm config set unsafe-perm true
      - run:
          name: test aws cli + permissions
          command: |
            aws s3 ls
      - run:
          name: run build and deploy script
          command: ./scripts/_deploy_preview_s3.sh
    
      # TODO: announce preview docs are ready
      # - run:
      #     <<: *defaults_slack_announcement

##
# Workflows
#
# CircleCI Workflow config
##
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_deploy_s3:
          context: org-global
          filters:
            branches:
              only:
                # TODO: change this to `mojaloop-docs-2.0`
                - /feat\/2282-.*/
